# Generated by Django 5.0.7 on 2024-08-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('nickname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
    ]
